language: python

addons:
  sonarcloud:
    organization: "revuel"

python:
  - "3.7"

script:
- make libs
- make coverage
- make sonar
- make build

deploy:
  provider: pypi
  user: __token__
  password: PYPI_TOKEN
  server: https://test.pypi.org/legacy/
  distributions: "sdist bdist_wheel"
  on:
    branch: staging
